theme: minima
title: Caffeinated Concatenation 
author: Megan Zamora
description: > # this means to ignore newlines until "baseurl:"
  A Technical Writer's journey to learn Python
  

# social links
github_username: mzgreg

show_excerpts: true # set to false to remove excerpts on the homepage
